version: '3.1'

services:

  donate2peope:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'donate2peope'
    ports:
      - 80:80
    volumes:
       - ./donate2people:/var/www/html

  database:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

  database-client:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DESIGN: haeckel
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 54320:8080
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025    